#ifndef MRUBY_GLib_CLASSES_HEADER
#define MRUBY_GLib_CLASSES_HEADER

/*
 * Class Bindings Options
 * ----------------------
 *
 * Use these macros to configure the generated bindings for classes & structs.
 *
 * Key:
 *
 * BIND_{type name}_TYPE                      : Should we bind the class at all?
 * BIND_{type name}_INITIALIZE                : If the class is bound, should we also bind initialize to malloc a new instance on `new`?
 * BIND_{type name}_{field name}_FIELD_READER : If the class is bound, should we also bind a reader for this field?
 * BIND_{type name}_{field name}_FIELD_WRITER : If the class is bound, should we also bind a writer for this field?
 * BIND_{type name}_{function name}_FUNCTION  : If the class is bound, should we also bind this member function?
 *
 * Fields & method are disabled by default so that bindings may be added and
 * tested incrementally.
 */

#define BIND_Argument_TYPE TRUE
#define BIND_Argument_INITIALIZE FALSE
#define BIND_Argument_a_FIELD_READER FALSE
#define BIND_Argument_a_FIELD_WRITER FALSE
#define BIND_Argument_type_FIELD_READER FALSE
#define BIND_Argument_type_FIELD_WRITER FALSE

#define BIND_Arguments_TYPE TRUE
#define BIND_Arguments_INITIALIZE FALSE
#define BIND_Arguments_arg_FIELD_READER FALSE
#define BIND_Arguments_arg_FIELD_WRITER FALSE
#define BIND_Arguments_count_FIELD_READER FALSE
#define BIND_Arguments_count_FIELD_WRITER FALSE
#define BIND_Arguments_direct_alloc_arg_FIELD_READER FALSE
#define BIND_Arguments_direct_alloc_arg_FIELD_WRITER FALSE

#define BIND_CharDirective_TYPE TRUE
#define BIND_CharDirective_INITIALIZE FALSE
#define BIND_CharDirective_arg_index_FIELD_READER FALSE
#define BIND_CharDirective_arg_index_FIELD_WRITER FALSE
#define BIND_CharDirective_conversion_FIELD_READER FALSE
#define BIND_CharDirective_conversion_FIELD_WRITER FALSE
#define BIND_CharDirective_dir_end_FIELD_READER FALSE
#define BIND_CharDirective_dir_end_FIELD_WRITER FALSE
#define BIND_CharDirective_dir_start_FIELD_READER FALSE
#define BIND_CharDirective_dir_start_FIELD_WRITER FALSE
#define BIND_CharDirective_flags_FIELD_READER FALSE
#define BIND_CharDirective_flags_FIELD_WRITER FALSE
#define BIND_CharDirective_precision_arg_index_FIELD_READER FALSE
#define BIND_CharDirective_precision_arg_index_FIELD_WRITER FALSE
#define BIND_CharDirective_precision_end_FIELD_READER FALSE
#define BIND_CharDirective_precision_end_FIELD_WRITER FALSE
#define BIND_CharDirective_precision_start_FIELD_READER FALSE
#define BIND_CharDirective_precision_start_FIELD_WRITER FALSE
#define BIND_CharDirective_width_arg_index_FIELD_READER FALSE
#define BIND_CharDirective_width_arg_index_FIELD_WRITER FALSE
#define BIND_CharDirective_width_end_FIELD_READER FALSE
#define BIND_CharDirective_width_end_FIELD_WRITER FALSE
#define BIND_CharDirective_width_start_FIELD_READER FALSE
#define BIND_CharDirective_width_start_FIELD_WRITER FALSE

#define BIND_CharDirectives_TYPE TRUE
#define BIND_CharDirectives_INITIALIZE FALSE
#define BIND_CharDirectives_count_FIELD_READER FALSE
#define BIND_CharDirectives_count_FIELD_WRITER FALSE
#define BIND_CharDirectives_dir_FIELD_READER FALSE
#define BIND_CharDirectives_dir_FIELD_WRITER FALSE
#define BIND_CharDirectives_direct_alloc_dir_FIELD_READER FALSE
#define BIND_CharDirectives_direct_alloc_dir_FIELD_WRITER FALSE
#define BIND_CharDirectives_max_precision_length_FIELD_READER FALSE
#define BIND_CharDirectives_max_precision_length_FIELD_WRITER FALSE
#define BIND_CharDirectives_max_width_length_FIELD_READER FALSE
#define BIND_CharDirectives_max_width_length_FIELD_WRITER FALSE

#define BIND_Decomposition_TYPE TRUE
#define BIND_Decomposition_INITIALIZE FALSE
#define BIND_Decomposition_canon_offset_FIELD_READER FALSE
#define BIND_Decomposition_canon_offset_FIELD_WRITER FALSE
#define BIND_Decomposition_ch_FIELD_READER FALSE
#define BIND_Decomposition_ch_FIELD_WRITER FALSE
#define BIND_Decomposition_compat_offset_FIELD_READER FALSE
#define BIND_Decomposition_compat_offset_FIELD_WRITER FALSE

#define BIND_DecompositionStep_TYPE TRUE
#define BIND_DecompositionStep_INITIALIZE FALSE
#define BIND_DecompositionStep_a_FIELD_READER FALSE
#define BIND_DecompositionStep_a_FIELD_WRITER FALSE
#define BIND_DecompositionStep_b_FIELD_READER FALSE
#define BIND_DecompositionStep_b_FIELD_WRITER FALSE
#define BIND_DecompositionStep_ch_FIELD_READER FALSE
#define BIND_DecompositionStep_ch_FIELD_WRITER FALSE

#define BIND_GBSearchConfig_TYPE TRUE
#define BIND_GBSearchConfig_INITIALIZE FALSE
#define BIND_GBSearchConfig_cmp_nodes_FIELD_READER FALSE
#define BIND_GBSearchConfig_cmp_nodes_FIELD_WRITER FALSE
#define BIND_GBSearchConfig_flags_FIELD_READER FALSE
#define BIND_GBSearchConfig_flags_FIELD_WRITER FALSE
#define BIND_GBSearchConfig_sizeof_node_FIELD_READER FALSE
#define BIND_GBSearchConfig_sizeof_node_FIELD_WRITER FALSE

#define BIND_GLibPrivateVTable_TYPE TRUE
#define BIND_GLibPrivateVTable_INITIALIZE FALSE
#define BIND_GLibPrivateVTable_g_check_setuid_FIELD_READER FALSE
#define BIND_GLibPrivateVTable_g_check_setuid_FIELD_WRITER FALSE
#define BIND_GLibPrivateVTable_g_dir_new_from_dirp_FIELD_READER FALSE
#define BIND_GLibPrivateVTable_g_dir_new_from_dirp_FIELD_WRITER FALSE
#define BIND_GLibPrivateVTable_g_dir_open_with_errno_FIELD_READER FALSE
#define BIND_GLibPrivateVTable_g_dir_open_with_errno_FIELD_WRITER FALSE
#define BIND_GLibPrivateVTable_g_get_worker_context_FIELD_READER FALSE
#define BIND_GLibPrivateVTable_g_get_worker_context_FIELD_WRITER FALSE
#define BIND_GLibPrivateVTable_g_main_context_new_with_next_id_FIELD_READER FALSE
#define BIND_GLibPrivateVTable_g_main_context_new_with_next_id_FIELD_WRITER FALSE
#define BIND_GLibPrivateVTable_g_wakeup_acknowledge_FIELD_READER FALSE
#define BIND_GLibPrivateVTable_g_wakeup_acknowledge_FIELD_WRITER FALSE
#define BIND_GLibPrivateVTable_g_wakeup_free_FIELD_READER FALSE
#define BIND_GLibPrivateVTable_g_wakeup_free_FIELD_WRITER FALSE
#define BIND_GLibPrivateVTable_g_wakeup_get_pollfd_FIELD_READER FALSE
#define BIND_GLibPrivateVTable_g_wakeup_get_pollfd_FIELD_WRITER FALSE
#define BIND_GLibPrivateVTable_g_wakeup_new_FIELD_READER FALSE
#define BIND_GLibPrivateVTable_g_wakeup_new_FIELD_WRITER FALSE
#define BIND_GLibPrivateVTable_g_wakeup_signal_FIELD_READER FALSE
#define BIND_GLibPrivateVTable_g_wakeup_signal_FIELD_WRITER FALSE
#define BIND_GLibPrivateVTable_glib_init_FIELD_READER FALSE
#define BIND_GLibPrivateVTable_glib_init_FIELD_WRITER FALSE

#define BIND_GTestConfig_TYPE TRUE
#define BIND_GTestConfig_INITIALIZE FALSE
#define BIND_GTestConfig_test_initialized_FIELD_READER FALSE
#define BIND_GTestConfig_test_initialized_FIELD_WRITER FALSE
#define BIND_GTestConfig_test_perf_FIELD_READER FALSE
#define BIND_GTestConfig_test_perf_FIELD_WRITER FALSE
#define BIND_GTestConfig_test_quick_FIELD_READER FALSE
#define BIND_GTestConfig_test_quick_FIELD_WRITER FALSE
#define BIND_GTestConfig_test_quiet_FIELD_READER FALSE
#define BIND_GTestConfig_test_quiet_FIELD_WRITER FALSE
#define BIND_GTestConfig_test_undefined_FIELD_READER FALSE
#define BIND_GTestConfig_test_undefined_FIELD_WRITER FALSE
#define BIND_GTestConfig_test_verbose_FIELD_READER FALSE
#define BIND_GTestConfig_test_verbose_FIELD_WRITER FALSE

#define BIND_GTestLogBuffer_TYPE TRUE
#define BIND_GTestLogBuffer_INITIALIZE FALSE
#define BIND_GTestLogBuffer_data_FIELD_READER FALSE
#define BIND_GTestLogBuffer_data_FIELD_WRITER FALSE
#define BIND_GTestLogBuffer_msgs_FIELD_READER FALSE
#define BIND_GTestLogBuffer_msgs_FIELD_WRITER FALSE

#define BIND_GTestLogMsg_TYPE TRUE
#define BIND_GTestLogMsg_INITIALIZE FALSE
#define BIND_GTestLogMsg_log_type_FIELD_READER FALSE
#define BIND_GTestLogMsg_log_type_FIELD_WRITER FALSE
#define BIND_GTestLogMsg_n_nums_FIELD_READER FALSE
#define BIND_GTestLogMsg_n_nums_FIELD_WRITER FALSE
#define BIND_GTestLogMsg_n_strings_FIELD_READER FALSE
#define BIND_GTestLogMsg_n_strings_FIELD_WRITER FALSE
#define BIND_GTestLogMsg_nums_FIELD_READER FALSE
#define BIND_GTestLogMsg_nums_FIELD_WRITER FALSE
#define BIND_GTestLogMsg_strings_FIELD_READER FALSE
#define BIND_GTestLogMsg_strings_FIELD_WRITER FALSE

#define BIND_GVariantMemberInfo_TYPE TRUE
#define BIND_GVariantMemberInfo_INITIALIZE FALSE
#define BIND_GVariantMemberInfo_a_FIELD_READER FALSE
#define BIND_GVariantMemberInfo_a_FIELD_WRITER FALSE
#define BIND_GVariantMemberInfo_b_FIELD_READER FALSE
#define BIND_GVariantMemberInfo_b_FIELD_WRITER FALSE
#define BIND_GVariantMemberInfo_c_FIELD_READER FALSE
#define BIND_GVariantMemberInfo_c_FIELD_WRITER FALSE
#define BIND_GVariantMemberInfo_ending_type_FIELD_READER FALSE
#define BIND_GVariantMemberInfo_ending_type_FIELD_WRITER FALSE
#define BIND_GVariantMemberInfo_i_FIELD_READER FALSE
#define BIND_GVariantMemberInfo_i_FIELD_WRITER FALSE
#define BIND_GVariantMemberInfo_type_info_FIELD_READER FALSE
#define BIND_GVariantMemberInfo_type_info_FIELD_WRITER FALSE

#define BIND_GVariantSerialised_TYPE TRUE
#define BIND_GVariantSerialised_INITIALIZE FALSE
#define BIND_GVariantSerialised_data_FIELD_READER FALSE
#define BIND_GVariantSerialised_data_FIELD_WRITER FALSE
#define BIND_GVariantSerialised_size_FIELD_READER FALSE
#define BIND_GVariantSerialised_size_FIELD_WRITER FALSE
#define BIND_GVariantSerialised_type_info_FIELD_READER FALSE
#define BIND_GVariantSerialised_type_info_FIELD_WRITER FALSE

#define BIND_GArray_TYPE TRUE
#define BIND_GArray_INITIALIZE FALSE
#define BIND_GArray_data_FIELD_READER FALSE
#define BIND_GArray_data_FIELD_WRITER FALSE
#define BIND_GArray_len_FIELD_READER FALSE
#define BIND_GArray_len_FIELD_WRITER FALSE

#define BIND_GAsyncQueue_TYPE TRUE
#define BIND_GAsyncQueue_INITIALIZE FALSE

#define BIND_GBookmarkFile_TYPE TRUE
#define BIND_GBookmarkFile_INITIALIZE FALSE

#define BIND_GByteArray_TYPE TRUE
#define BIND_GByteArray_INITIALIZE FALSE
#define BIND_GByteArray_data_FIELD_READER FALSE
#define BIND_GByteArray_data_FIELD_WRITER FALSE
#define BIND_GByteArray_len_FIELD_READER FALSE
#define BIND_GByteArray_len_FIELD_WRITER FALSE

#define BIND_GBytes_TYPE TRUE
#define BIND_GBytes_INITIALIZE FALSE

#define BIND_GChecksum_TYPE TRUE
#define BIND_GChecksum_INITIALIZE FALSE

#define BIND_GCond_TYPE TRUE
#define BIND_GCond_INITIALIZE FALSE
#define BIND_GCond_i_FIELD_READER FALSE
#define BIND_GCond_i_FIELD_WRITER FALSE
#define BIND_GCond_p_FIELD_READER FALSE
#define BIND_GCond_p_FIELD_WRITER FALSE

#define BIND_GData_TYPE TRUE
#define BIND_GData_INITIALIZE FALSE

#define BIND_GDate_TYPE TRUE
#define BIND_GDate_INITIALIZE FALSE
#define BIND_GDate_day_FIELD_READER FALSE
#define BIND_GDate_day_FIELD_WRITER FALSE
#define BIND_GDate_dmy_FIELD_READER FALSE
#define BIND_GDate_dmy_FIELD_WRITER FALSE
#define BIND_GDate_julian_FIELD_READER FALSE
#define BIND_GDate_julian_FIELD_WRITER FALSE
#define BIND_GDate_julian_days_FIELD_READER FALSE
#define BIND_GDate_julian_days_FIELD_WRITER FALSE
#define BIND_GDate_month_FIELD_READER FALSE
#define BIND_GDate_month_FIELD_WRITER FALSE
#define BIND_GDate_year_FIELD_READER FALSE
#define BIND_GDate_year_FIELD_WRITER FALSE

#define BIND_GDateTime_TYPE TRUE
#define BIND_GDateTime_INITIALIZE FALSE

#define BIND_GDebugKey_TYPE TRUE
#define BIND_GDebugKey_INITIALIZE FALSE
#define BIND_GDebugKey_key_FIELD_READER FALSE
#define BIND_GDebugKey_key_FIELD_WRITER FALSE
#define BIND_GDebugKey_value_FIELD_READER FALSE
#define BIND_GDebugKey_value_FIELD_WRITER FALSE

#define BIND_GDir_TYPE TRUE
#define BIND_GDir_INITIALIZE FALSE

#define BIND_GError_TYPE TRUE
#define BIND_GError_INITIALIZE FALSE
#define BIND_GError_code_FIELD_READER FALSE
#define BIND_GError_code_FIELD_WRITER FALSE
#define BIND_GError_domain_FIELD_READER FALSE
#define BIND_GError_domain_FIELD_WRITER FALSE
#define BIND_GError_message_FIELD_READER FALSE
#define BIND_GError_message_FIELD_WRITER FALSE

#define BIND_GHashTable_TYPE TRUE
#define BIND_GHashTable_INITIALIZE FALSE

#define BIND_GHashTableIter_TYPE TRUE
#define BIND_GHashTableIter_INITIALIZE FALSE
#define BIND_GHashTableIter_dummy1_FIELD_READER FALSE
#define BIND_GHashTableIter_dummy1_FIELD_WRITER FALSE
#define BIND_GHashTableIter_dummy2_FIELD_READER FALSE
#define BIND_GHashTableIter_dummy2_FIELD_WRITER FALSE
#define BIND_GHashTableIter_dummy3_FIELD_READER FALSE
#define BIND_GHashTableIter_dummy3_FIELD_WRITER FALSE
#define BIND_GHashTableIter_dummy4_FIELD_READER FALSE
#define BIND_GHashTableIter_dummy4_FIELD_WRITER FALSE
#define BIND_GHashTableIter_dummy5_FIELD_READER FALSE
#define BIND_GHashTableIter_dummy5_FIELD_WRITER FALSE
#define BIND_GHashTableIter_dummy6_FIELD_READER FALSE
#define BIND_GHashTableIter_dummy6_FIELD_WRITER FALSE

#define BIND_GHmac_TYPE TRUE
#define BIND_GHmac_INITIALIZE FALSE

#define BIND_GHook_TYPE TRUE
#define BIND_GHook_INITIALIZE FALSE
#define BIND_GHook_data_FIELD_READER FALSE
#define BIND_GHook_data_FIELD_WRITER FALSE
#define BIND_GHook_destroy_FIELD_READER FALSE
#define BIND_GHook_destroy_FIELD_WRITER FALSE
#define BIND_GHook_flags_FIELD_READER FALSE
#define BIND_GHook_flags_FIELD_WRITER FALSE
#define BIND_GHook_func_FIELD_READER FALSE
#define BIND_GHook_func_FIELD_WRITER FALSE
#define BIND_GHook_hook_id_FIELD_READER FALSE
#define BIND_GHook_hook_id_FIELD_WRITER FALSE
#define BIND_GHook_next_FIELD_READER FALSE
#define BIND_GHook_next_FIELD_WRITER FALSE
#define BIND_GHook_prev_FIELD_READER FALSE
#define BIND_GHook_prev_FIELD_WRITER FALSE
#define BIND_GHook_ref_count_FIELD_READER FALSE
#define BIND_GHook_ref_count_FIELD_WRITER FALSE

#define BIND_GHookList_TYPE TRUE
#define BIND_GHookList_INITIALIZE FALSE
#define BIND_GHookList_dummy_FIELD_READER FALSE
#define BIND_GHookList_dummy_FIELD_WRITER FALSE
#define BIND_GHookList_dummy3_FIELD_READER FALSE
#define BIND_GHookList_dummy3_FIELD_WRITER FALSE
#define BIND_GHookList_finalize_hook_FIELD_READER FALSE
#define BIND_GHookList_finalize_hook_FIELD_WRITER FALSE
#define BIND_GHookList_hook_size_FIELD_READER FALSE
#define BIND_GHookList_hook_size_FIELD_WRITER FALSE
#define BIND_GHookList_hooks_FIELD_READER FALSE
#define BIND_GHookList_hooks_FIELD_WRITER FALSE
#define BIND_GHookList_is_setup_FIELD_READER FALSE
#define BIND_GHookList_is_setup_FIELD_WRITER FALSE
#define BIND_GHookList_seq_id_FIELD_READER FALSE
#define BIND_GHookList_seq_id_FIELD_WRITER FALSE

#define BIND_GIConv_TYPE TRUE
#define BIND_GIConv_INITIALIZE FALSE

#define BIND_GIOChannel_TYPE TRUE
#define BIND_GIOChannel_INITIALIZE FALSE
#define BIND_GIOChannel_buf_size_FIELD_READER FALSE
#define BIND_GIOChannel_buf_size_FIELD_WRITER FALSE
#define BIND_GIOChannel_close_on_unref_FIELD_READER FALSE
#define BIND_GIOChannel_close_on_unref_FIELD_WRITER FALSE
#define BIND_GIOChannel_do_encode_FIELD_READER FALSE
#define BIND_GIOChannel_do_encode_FIELD_WRITER FALSE
#define BIND_GIOChannel_encoded_read_buf_FIELD_READER FALSE
#define BIND_GIOChannel_encoded_read_buf_FIELD_WRITER FALSE
#define BIND_GIOChannel_encoding_FIELD_READER FALSE
#define BIND_GIOChannel_encoding_FIELD_WRITER FALSE
#define BIND_GIOChannel_funcs_FIELD_READER FALSE
#define BIND_GIOChannel_funcs_FIELD_WRITER FALSE
#define BIND_GIOChannel_is_readable_FIELD_READER FALSE
#define BIND_GIOChannel_is_readable_FIELD_WRITER FALSE
#define BIND_GIOChannel_is_seekable_FIELD_READER FALSE
#define BIND_GIOChannel_is_seekable_FIELD_WRITER FALSE
#define BIND_GIOChannel_is_writeable_FIELD_READER FALSE
#define BIND_GIOChannel_is_writeable_FIELD_WRITER FALSE
#define BIND_GIOChannel_line_term_FIELD_READER FALSE
#define BIND_GIOChannel_line_term_FIELD_WRITER FALSE
#define BIND_GIOChannel_line_term_len_FIELD_READER FALSE
#define BIND_GIOChannel_line_term_len_FIELD_WRITER FALSE
#define BIND_GIOChannel_partial_write_buf_FIELD_READER FALSE
#define BIND_GIOChannel_partial_write_buf_FIELD_WRITER FALSE
#define BIND_GIOChannel_read_buf_FIELD_READER FALSE
#define BIND_GIOChannel_read_buf_FIELD_WRITER FALSE
#define BIND_GIOChannel_read_cd_FIELD_READER FALSE
#define BIND_GIOChannel_read_cd_FIELD_WRITER FALSE
#define BIND_GIOChannel_ref_count_FIELD_READER FALSE
#define BIND_GIOChannel_ref_count_FIELD_WRITER FALSE
#define BIND_GIOChannel_reserved1_FIELD_READER FALSE
#define BIND_GIOChannel_reserved1_FIELD_WRITER FALSE
#define BIND_GIOChannel_reserved2_FIELD_READER FALSE
#define BIND_GIOChannel_reserved2_FIELD_WRITER FALSE
#define BIND_GIOChannel_use_buffer_FIELD_READER FALSE
#define BIND_GIOChannel_use_buffer_FIELD_WRITER FALSE
#define BIND_GIOChannel_write_buf_FIELD_READER FALSE
#define BIND_GIOChannel_write_buf_FIELD_WRITER FALSE
#define BIND_GIOChannel_write_cd_FIELD_READER FALSE
#define BIND_GIOChannel_write_cd_FIELD_WRITER FALSE

#define BIND_GIOFuncs_TYPE TRUE
#define BIND_GIOFuncs_INITIALIZE FALSE
#define BIND_GIOFuncs_io_close_FIELD_READER FALSE
#define BIND_GIOFuncs_io_close_FIELD_WRITER FALSE
#define BIND_GIOFuncs_io_create_watch_FIELD_READER FALSE
#define BIND_GIOFuncs_io_create_watch_FIELD_WRITER FALSE
#define BIND_GIOFuncs_io_free_FIELD_READER FALSE
#define BIND_GIOFuncs_io_free_FIELD_WRITER FALSE
#define BIND_GIOFuncs_io_get_flags_FIELD_READER FALSE
#define BIND_GIOFuncs_io_get_flags_FIELD_WRITER FALSE
#define BIND_GIOFuncs_io_read_FIELD_READER FALSE
#define BIND_GIOFuncs_io_read_FIELD_WRITER FALSE
#define BIND_GIOFuncs_io_seek_FIELD_READER FALSE
#define BIND_GIOFuncs_io_seek_FIELD_WRITER FALSE
#define BIND_GIOFuncs_io_set_flags_FIELD_READER FALSE
#define BIND_GIOFuncs_io_set_flags_FIELD_WRITER FALSE
#define BIND_GIOFuncs_io_write_FIELD_READER FALSE
#define BIND_GIOFuncs_io_write_FIELD_WRITER FALSE

#define BIND_GKeyFile_TYPE TRUE
#define BIND_GKeyFile_INITIALIZE FALSE

#define BIND_GList_TYPE TRUE
#define BIND_GList_INITIALIZE FALSE
#define BIND_GList_data_FIELD_READER FALSE
#define BIND_GList_data_FIELD_WRITER FALSE
#define BIND_GList_next_FIELD_READER FALSE
#define BIND_GList_next_FIELD_WRITER FALSE
#define BIND_GList_prev_FIELD_READER FALSE
#define BIND_GList_prev_FIELD_WRITER FALSE

#define BIND_GMainContext_TYPE TRUE
#define BIND_GMainContext_INITIALIZE FALSE

#define BIND_GMainLoop_TYPE TRUE
#define BIND_GMainLoop_INITIALIZE FALSE

#define BIND_GMappedFile_TYPE TRUE
#define BIND_GMappedFile_INITIALIZE FALSE

#define BIND_GMarkupParseContext_TYPE TRUE
#define BIND_GMarkupParseContext_INITIALIZE FALSE

#define BIND_GMarkupParser_TYPE TRUE
#define BIND_GMarkupParser_INITIALIZE FALSE
#define BIND_GMarkupParser_end_element_FIELD_READER FALSE
#define BIND_GMarkupParser_end_element_FIELD_WRITER FALSE
#define BIND_GMarkupParser_error_FIELD_READER FALSE
#define BIND_GMarkupParser_error_FIELD_WRITER FALSE
#define BIND_GMarkupParser_passthrough_FIELD_READER FALSE
#define BIND_GMarkupParser_passthrough_FIELD_WRITER FALSE
#define BIND_GMarkupParser_start_element_FIELD_READER FALSE
#define BIND_GMarkupParser_start_element_FIELD_WRITER FALSE
#define BIND_GMarkupParser_text_FIELD_READER FALSE
#define BIND_GMarkupParser_text_FIELD_WRITER FALSE

#define BIND_GMatchInfo_TYPE TRUE
#define BIND_GMatchInfo_INITIALIZE FALSE

#define BIND_GMemVTable_TYPE TRUE
#define BIND_GMemVTable_INITIALIZE FALSE
#define BIND_GMemVTable_calloc_FIELD_READER FALSE
#define BIND_GMemVTable_calloc_FIELD_WRITER FALSE
#define BIND_GMemVTable_free_FIELD_READER FALSE
#define BIND_GMemVTable_free_FIELD_WRITER FALSE
#define BIND_GMemVTable_malloc_FIELD_READER FALSE
#define BIND_GMemVTable_malloc_FIELD_WRITER FALSE
#define BIND_GMemVTable_realloc_FIELD_READER FALSE
#define BIND_GMemVTable_realloc_FIELD_WRITER FALSE
#define BIND_GMemVTable_try_malloc_FIELD_READER FALSE
#define BIND_GMemVTable_try_malloc_FIELD_WRITER FALSE
#define BIND_GMemVTable_try_realloc_FIELD_READER FALSE
#define BIND_GMemVTable_try_realloc_FIELD_WRITER FALSE

#define BIND_GNode_TYPE TRUE
#define BIND_GNode_INITIALIZE FALSE
#define BIND_GNode_children_FIELD_READER FALSE
#define BIND_GNode_children_FIELD_WRITER FALSE
#define BIND_GNode_data_FIELD_READER FALSE
#define BIND_GNode_data_FIELD_WRITER FALSE
#define BIND_GNode_next_FIELD_READER FALSE
#define BIND_GNode_next_FIELD_WRITER FALSE
#define BIND_GNode_parent_FIELD_READER FALSE
#define BIND_GNode_parent_FIELD_WRITER FALSE
#define BIND_GNode_prev_FIELD_READER FALSE
#define BIND_GNode_prev_FIELD_WRITER FALSE

#define BIND_GOnce_TYPE TRUE
#define BIND_GOnce_INITIALIZE FALSE
#define BIND_GOnce_retval_FIELD_READER FALSE
#define BIND_GOnce_retval_FIELD_WRITER FALSE
#define BIND_GOnce_status_FIELD_READER FALSE
#define BIND_GOnce_status_FIELD_WRITER FALSE

#define BIND_GOptionContext_TYPE TRUE
#define BIND_GOptionContext_INITIALIZE FALSE

#define BIND_GOptionEntry_TYPE TRUE
#define BIND_GOptionEntry_INITIALIZE FALSE
#define BIND_GOptionEntry_arg_FIELD_READER FALSE
#define BIND_GOptionEntry_arg_FIELD_WRITER FALSE
#define BIND_GOptionEntry_arg_data_FIELD_READER FALSE
#define BIND_GOptionEntry_arg_data_FIELD_WRITER FALSE
#define BIND_GOptionEntry_arg_description_FIELD_READER FALSE
#define BIND_GOptionEntry_arg_description_FIELD_WRITER FALSE
#define BIND_GOptionEntry_description_FIELD_READER FALSE
#define BIND_GOptionEntry_description_FIELD_WRITER FALSE
#define BIND_GOptionEntry_flags_FIELD_READER FALSE
#define BIND_GOptionEntry_flags_FIELD_WRITER FALSE
#define BIND_GOptionEntry_long_name_FIELD_READER FALSE
#define BIND_GOptionEntry_long_name_FIELD_WRITER FALSE
#define BIND_GOptionEntry_short_name_FIELD_READER FALSE
#define BIND_GOptionEntry_short_name_FIELD_WRITER FALSE

#define BIND_GOptionGroup_TYPE TRUE
#define BIND_GOptionGroup_INITIALIZE FALSE

#define BIND_GPatternSpec_TYPE TRUE
#define BIND_GPatternSpec_INITIALIZE FALSE

#define BIND_GPollFD_TYPE TRUE
#define BIND_GPollFD_INITIALIZE FALSE
#define BIND_GPollFD_events_FIELD_READER FALSE
#define BIND_GPollFD_events_FIELD_WRITER FALSE
#define BIND_GPollFD_fd_FIELD_READER FALSE
#define BIND_GPollFD_fd_FIELD_WRITER FALSE
#define BIND_GPollFD_revents_FIELD_READER FALSE
#define BIND_GPollFD_revents_FIELD_WRITER FALSE

#define BIND_GPrivate_TYPE TRUE
#define BIND_GPrivate_INITIALIZE FALSE
#define BIND_GPrivate_future_FIELD_READER FALSE
#define BIND_GPrivate_future_FIELD_WRITER FALSE
#define BIND_GPrivate_notify_FIELD_READER FALSE
#define BIND_GPrivate_notify_FIELD_WRITER FALSE
#define BIND_GPrivate_p_FIELD_READER FALSE
#define BIND_GPrivate_p_FIELD_WRITER FALSE

#define BIND_GPtrArray_TYPE TRUE
#define BIND_GPtrArray_INITIALIZE FALSE
#define BIND_GPtrArray_len_FIELD_READER FALSE
#define BIND_GPtrArray_len_FIELD_WRITER FALSE
#define BIND_GPtrArray_pdata_FIELD_READER FALSE
#define BIND_GPtrArray_pdata_FIELD_WRITER FALSE

#define BIND_GQueue_TYPE TRUE
#define BIND_GQueue_INITIALIZE FALSE
#define BIND_GQueue_head_FIELD_READER FALSE
#define BIND_GQueue_head_FIELD_WRITER FALSE
#define BIND_GQueue_length_FIELD_READER FALSE
#define BIND_GQueue_length_FIELD_WRITER FALSE
#define BIND_GQueue_tail_FIELD_READER FALSE
#define BIND_GQueue_tail_FIELD_WRITER FALSE

#define BIND_GRand_TYPE TRUE
#define BIND_GRand_INITIALIZE FALSE

#define BIND_GRealThread_TYPE TRUE
#define BIND_GRealThread_INITIALIZE FALSE
#define BIND_GRealThread_name_FIELD_READER FALSE
#define BIND_GRealThread_name_FIELD_WRITER FALSE
#define BIND_GRealThread_ours_FIELD_READER FALSE
#define BIND_GRealThread_ours_FIELD_WRITER FALSE
#define BIND_GRealThread_ref_count_FIELD_READER FALSE
#define BIND_GRealThread_ref_count_FIELD_WRITER FALSE
#define BIND_GRealThread_retval_FIELD_READER FALSE
#define BIND_GRealThread_retval_FIELD_WRITER FALSE
#define BIND_GRealThread_thread_FIELD_READER FALSE
#define BIND_GRealThread_thread_FIELD_WRITER FALSE

#define BIND_GRecMutex_TYPE TRUE
#define BIND_GRecMutex_INITIALIZE FALSE
#define BIND_GRecMutex_i_FIELD_READER FALSE
#define BIND_GRecMutex_i_FIELD_WRITER FALSE
#define BIND_GRecMutex_p_FIELD_READER FALSE
#define BIND_GRecMutex_p_FIELD_WRITER FALSE

#define BIND_GRegex_TYPE TRUE
#define BIND_GRegex_INITIALIZE FALSE

#define BIND_GRWLock_TYPE TRUE
#define BIND_GRWLock_INITIALIZE FALSE
#define BIND_GRWLock_i_FIELD_READER FALSE
#define BIND_GRWLock_i_FIELD_WRITER FALSE
#define BIND_GRWLock_p_FIELD_READER FALSE
#define BIND_GRWLock_p_FIELD_WRITER FALSE

#define BIND_GScanner_TYPE TRUE
#define BIND_GScanner_INITIALIZE FALSE
#define BIND_GScanner_buffer_FIELD_READER FALSE
#define BIND_GScanner_buffer_FIELD_WRITER FALSE
#define BIND_GScanner_config_FIELD_READER FALSE
#define BIND_GScanner_config_FIELD_WRITER FALSE
#define BIND_GScanner_input_fd_FIELD_READER FALSE
#define BIND_GScanner_input_fd_FIELD_WRITER FALSE
#define BIND_GScanner_input_name_FIELD_READER FALSE
#define BIND_GScanner_input_name_FIELD_WRITER FALSE
#define BIND_GScanner_line_FIELD_READER FALSE
#define BIND_GScanner_line_FIELD_WRITER FALSE
#define BIND_GScanner_max_parse_errors_FIELD_READER FALSE
#define BIND_GScanner_max_parse_errors_FIELD_WRITER FALSE
#define BIND_GScanner_msg_handler_FIELD_READER FALSE
#define BIND_GScanner_msg_handler_FIELD_WRITER FALSE
#define BIND_GScanner_next_line_FIELD_READER FALSE
#define BIND_GScanner_next_line_FIELD_WRITER FALSE
#define BIND_GScanner_next_position_FIELD_READER FALSE
#define BIND_GScanner_next_position_FIELD_WRITER FALSE
#define BIND_GScanner_next_token_FIELD_READER FALSE
#define BIND_GScanner_next_token_FIELD_WRITER FALSE
#define BIND_GScanner_next_value_FIELD_READER FALSE
#define BIND_GScanner_next_value_FIELD_WRITER FALSE
#define BIND_GScanner_parse_errors_FIELD_READER FALSE
#define BIND_GScanner_parse_errors_FIELD_WRITER FALSE
#define BIND_GScanner_position_FIELD_READER FALSE
#define BIND_GScanner_position_FIELD_WRITER FALSE
#define BIND_GScanner_qdata_FIELD_READER FALSE
#define BIND_GScanner_qdata_FIELD_WRITER FALSE
#define BIND_GScanner_scope_id_FIELD_READER FALSE
#define BIND_GScanner_scope_id_FIELD_WRITER FALSE
#define BIND_GScanner_symbol_table_FIELD_READER FALSE
#define BIND_GScanner_symbol_table_FIELD_WRITER FALSE
#define BIND_GScanner_text_FIELD_READER FALSE
#define BIND_GScanner_text_FIELD_WRITER FALSE
#define BIND_GScanner_text_end_FIELD_READER FALSE
#define BIND_GScanner_text_end_FIELD_WRITER FALSE
#define BIND_GScanner_token_FIELD_READER FALSE
#define BIND_GScanner_token_FIELD_WRITER FALSE
#define BIND_GScanner_user_data_FIELD_READER FALSE
#define BIND_GScanner_user_data_FIELD_WRITER FALSE
#define BIND_GScanner_value_FIELD_READER FALSE
#define BIND_GScanner_value_FIELD_WRITER FALSE

#define BIND_GScannerConfig_TYPE TRUE
#define BIND_GScannerConfig_INITIALIZE FALSE
#define BIND_GScannerConfig_case_sensitive_FIELD_READER FALSE
#define BIND_GScannerConfig_case_sensitive_FIELD_WRITER FALSE
#define BIND_GScannerConfig_char_2_token_FIELD_READER FALSE
#define BIND_GScannerConfig_char_2_token_FIELD_WRITER FALSE
#define BIND_GScannerConfig_cpair_comment_single_FIELD_READER FALSE
#define BIND_GScannerConfig_cpair_comment_single_FIELD_WRITER FALSE
#define BIND_GScannerConfig_cset_identifier_first_FIELD_READER FALSE
#define BIND_GScannerConfig_cset_identifier_first_FIELD_WRITER FALSE
#define BIND_GScannerConfig_cset_identifier_nth_FIELD_READER FALSE
#define BIND_GScannerConfig_cset_identifier_nth_FIELD_WRITER FALSE
#define BIND_GScannerConfig_cset_skip_characters_FIELD_READER FALSE
#define BIND_GScannerConfig_cset_skip_characters_FIELD_WRITER FALSE
#define BIND_GScannerConfig_identifier_2_string_FIELD_READER FALSE
#define BIND_GScannerConfig_identifier_2_string_FIELD_WRITER FALSE
#define BIND_GScannerConfig_int_2_float_FIELD_READER FALSE
#define BIND_GScannerConfig_int_2_float_FIELD_WRITER FALSE
#define BIND_GScannerConfig_numbers_2_int_FIELD_READER FALSE
#define BIND_GScannerConfig_numbers_2_int_FIELD_WRITER FALSE
#define BIND_GScannerConfig_padding_dummy_FIELD_READER FALSE
#define BIND_GScannerConfig_padding_dummy_FIELD_WRITER FALSE
#define BIND_GScannerConfig_scan_binary_FIELD_READER FALSE
#define BIND_GScannerConfig_scan_binary_FIELD_WRITER FALSE
#define BIND_GScannerConfig_scan_comment_multi_FIELD_READER FALSE
#define BIND_GScannerConfig_scan_comment_multi_FIELD_WRITER FALSE
#define BIND_GScannerConfig_scan_float_FIELD_READER FALSE
#define BIND_GScannerConfig_scan_float_FIELD_WRITER FALSE
#define BIND_GScannerConfig_scan_hex_FIELD_READER FALSE
#define BIND_GScannerConfig_scan_hex_FIELD_WRITER FALSE
#define BIND_GScannerConfig_scan_hex_dollar_FIELD_READER FALSE
#define BIND_GScannerConfig_scan_hex_dollar_FIELD_WRITER FALSE
#define BIND_GScannerConfig_scan_identifier_FIELD_READER FALSE
#define BIND_GScannerConfig_scan_identifier_FIELD_WRITER FALSE
#define BIND_GScannerConfig_scan_identifier_1char_FIELD_READER FALSE
#define BIND_GScannerConfig_scan_identifier_1char_FIELD_WRITER FALSE
#define BIND_GScannerConfig_scan_identifier_NULL_FIELD_READER FALSE
#define BIND_GScannerConfig_scan_identifier_NULL_FIELD_WRITER FALSE
#define BIND_GScannerConfig_scan_octal_FIELD_READER FALSE
#define BIND_GScannerConfig_scan_octal_FIELD_WRITER FALSE
#define BIND_GScannerConfig_scan_string_dq_FIELD_READER FALSE
#define BIND_GScannerConfig_scan_string_dq_FIELD_WRITER FALSE
#define BIND_GScannerConfig_scan_string_sq_FIELD_READER FALSE
#define BIND_GScannerConfig_scan_string_sq_FIELD_WRITER FALSE
#define BIND_GScannerConfig_scan_symbols_FIELD_READER FALSE
#define BIND_GScannerConfig_scan_symbols_FIELD_WRITER FALSE
#define BIND_GScannerConfig_scope_0_fallback_FIELD_READER FALSE
#define BIND_GScannerConfig_scope_0_fallback_FIELD_WRITER FALSE
#define BIND_GScannerConfig_skip_comment_multi_FIELD_READER FALSE
#define BIND_GScannerConfig_skip_comment_multi_FIELD_WRITER FALSE
#define BIND_GScannerConfig_skip_comment_single_FIELD_READER FALSE
#define BIND_GScannerConfig_skip_comment_single_FIELD_WRITER FALSE
#define BIND_GScannerConfig_store_int64_FIELD_READER FALSE
#define BIND_GScannerConfig_store_int64_FIELD_WRITER FALSE
#define BIND_GScannerConfig_symbol_2_token_FIELD_READER FALSE
#define BIND_GScannerConfig_symbol_2_token_FIELD_WRITER FALSE

#define BIND_GSequence_TYPE TRUE
#define BIND_GSequence_INITIALIZE FALSE

#define BIND_GSequenceNode_TYPE TRUE
#define BIND_GSequenceNode_INITIALIZE FALSE

#define BIND_GSList_TYPE TRUE
#define BIND_GSList_INITIALIZE FALSE
#define BIND_GSList_data_FIELD_READER FALSE
#define BIND_GSList_data_FIELD_WRITER FALSE
#define BIND_GSList_next_FIELD_READER FALSE
#define BIND_GSList_next_FIELD_WRITER FALSE

#define BIND_GSource_TYPE TRUE
#define BIND_GSource_INITIALIZE FALSE
#define BIND_GSource_callback_data_FIELD_READER FALSE
#define BIND_GSource_callback_data_FIELD_WRITER FALSE
#define BIND_GSource_callback_funcs_FIELD_READER FALSE
#define BIND_GSource_callback_funcs_FIELD_WRITER FALSE
#define BIND_GSource_context_FIELD_READER FALSE
#define BIND_GSource_context_FIELD_WRITER FALSE
#define BIND_GSource_flags_FIELD_READER FALSE
#define BIND_GSource_flags_FIELD_WRITER FALSE
#define BIND_GSource_name_FIELD_READER FALSE
#define BIND_GSource_name_FIELD_WRITER FALSE
#define BIND_GSource_next_FIELD_READER FALSE
#define BIND_GSource_next_FIELD_WRITER FALSE
#define BIND_GSource_poll_fds_FIELD_READER FALSE
#define BIND_GSource_poll_fds_FIELD_WRITER FALSE
#define BIND_GSource_prev_FIELD_READER FALSE
#define BIND_GSource_prev_FIELD_WRITER FALSE
#define BIND_GSource_priority_FIELD_READER FALSE
#define BIND_GSource_priority_FIELD_WRITER FALSE
#define BIND_GSource_priv_FIELD_READER FALSE
#define BIND_GSource_priv_FIELD_WRITER FALSE
#define BIND_GSource_ref_count_FIELD_READER FALSE
#define BIND_GSource_ref_count_FIELD_WRITER FALSE
#define BIND_GSource_source_funcs_FIELD_READER FALSE
#define BIND_GSource_source_funcs_FIELD_WRITER FALSE
#define BIND_GSource_source_id_FIELD_READER FALSE
#define BIND_GSource_source_id_FIELD_WRITER FALSE

#define BIND_GSourceCallbackFuncs_TYPE TRUE
#define BIND_GSourceCallbackFuncs_INITIALIZE FALSE
#define BIND_GSourceCallbackFuncs_get_FIELD_READER FALSE
#define BIND_GSourceCallbackFuncs_get_FIELD_WRITER FALSE
#define BIND_GSourceCallbackFuncs_ref_FIELD_READER FALSE
#define BIND_GSourceCallbackFuncs_ref_FIELD_WRITER FALSE
#define BIND_GSourceCallbackFuncs_unref_FIELD_READER FALSE
#define BIND_GSourceCallbackFuncs_unref_FIELD_WRITER FALSE

#define BIND_GSourceFuncs_TYPE TRUE
#define BIND_GSourceFuncs_INITIALIZE FALSE
#define BIND_GSourceFuncs_check_FIELD_READER FALSE
#define BIND_GSourceFuncs_check_FIELD_WRITER FALSE
#define BIND_GSourceFuncs_closure_callback_FIELD_READER FALSE
#define BIND_GSourceFuncs_closure_callback_FIELD_WRITER FALSE
#define BIND_GSourceFuncs_closure_marshal_FIELD_READER FALSE
#define BIND_GSourceFuncs_closure_marshal_FIELD_WRITER FALSE
#define BIND_GSourceFuncs_dispatch_FIELD_READER FALSE
#define BIND_GSourceFuncs_dispatch_FIELD_WRITER FALSE
#define BIND_GSourceFuncs_finalize_FIELD_READER FALSE
#define BIND_GSourceFuncs_finalize_FIELD_WRITER FALSE
#define BIND_GSourceFuncs_prepare_FIELD_READER FALSE
#define BIND_GSourceFuncs_prepare_FIELD_WRITER FALSE

#define BIND_GSourcePrivate_TYPE TRUE
#define BIND_GSourcePrivate_INITIALIZE FALSE

#define BIND_GString_TYPE TRUE
#define BIND_GString_INITIALIZE FALSE
#define BIND_GString_allocated_len_FIELD_READER FALSE
#define BIND_GString_allocated_len_FIELD_WRITER FALSE
#define BIND_GString_len_FIELD_READER FALSE
#define BIND_GString_len_FIELD_WRITER FALSE
#define BIND_GString_str_FIELD_READER FALSE
#define BIND_GString_str_FIELD_WRITER FALSE

#define BIND_GStringChunk_TYPE TRUE
#define BIND_GStringChunk_INITIALIZE FALSE

#define BIND_GThread_TYPE TRUE
#define BIND_GThread_INITIALIZE FALSE

#define BIND_GThreadPool_TYPE TRUE
#define BIND_GThreadPool_INITIALIZE FALSE
#define BIND_GThreadPool_exclusive_FIELD_READER FALSE
#define BIND_GThreadPool_exclusive_FIELD_WRITER FALSE
#define BIND_GThreadPool_func_FIELD_READER FALSE
#define BIND_GThreadPool_func_FIELD_WRITER FALSE
#define BIND_GThreadPool_user_data_FIELD_READER FALSE
#define BIND_GThreadPool_user_data_FIELD_WRITER FALSE

#define BIND_GTimer_TYPE TRUE
#define BIND_GTimer_INITIALIZE FALSE

#define BIND_GTimeVal_TYPE TRUE
#define BIND_GTimeVal_INITIALIZE FALSE
#define BIND_GTimeVal_tv_sec_FIELD_READER FALSE
#define BIND_GTimeVal_tv_sec_FIELD_WRITER FALSE
#define BIND_GTimeVal_tv_usec_FIELD_READER FALSE
#define BIND_GTimeVal_tv_usec_FIELD_WRITER FALSE

#define BIND_GTimeZone_TYPE TRUE
#define BIND_GTimeZone_INITIALIZE FALSE

#define BIND_GTrashStack_TYPE TRUE
#define BIND_GTrashStack_INITIALIZE FALSE
#define BIND_GTrashStack_next_FIELD_READER FALSE
#define BIND_GTrashStack_next_FIELD_WRITER FALSE

#define BIND_GTree_TYPE TRUE
#define BIND_GTree_INITIALIZE FALSE

#define BIND_GVariant_TYPE TRUE
#define BIND_GVariant_INITIALIZE FALSE

#define BIND_GVariantBuilder_TYPE TRUE
#define BIND_GVariantBuilder_INITIALIZE FALSE
#define BIND_GVariantBuilder_x_FIELD_READER FALSE
#define BIND_GVariantBuilder_x_FIELD_WRITER FALSE

#define BIND_GVariantDict_TYPE TRUE
#define BIND_GVariantDict_INITIALIZE FALSE
#define BIND_GVariantDict_x_FIELD_READER FALSE
#define BIND_GVariantDict_x_FIELD_WRITER FALSE

#define BIND_GVariantIter_TYPE TRUE
#define BIND_GVariantIter_INITIALIZE FALSE
#define BIND_GVariantIter_x_FIELD_READER FALSE
#define BIND_GVariantIter_x_FIELD_WRITER FALSE

#define BIND_GVariantType_TYPE TRUE
#define BIND_GVariantType_INITIALIZE FALSE

#define BIND_GVariantTypeInfo_TYPE TRUE
#define BIND_GVariantTypeInfo_INITIALIZE FALSE

#define BIND_GWakeup_TYPE TRUE
#define BIND_GWakeup_INITIALIZE FALSE

#define BIND_GTestCase_TYPE TRUE
#define BIND_GTestCase_INITIALIZE FALSE

#define BIND_GTestSuite_TYPE TRUE
#define BIND_GTestSuite_INITIALIZE FALSE

#define BIND_Interval_TYPE TRUE
#define BIND_Interval_INITIALIZE FALSE
#define BIND_Interval_end_FIELD_READER FALSE
#define BIND_Interval_end_FIELD_WRITER FALSE
#define BIND_Interval_start_FIELD_READER FALSE
#define BIND_Interval_start_FIELD_WRITER FALSE

#define BIND_LocaleEntry_TYPE TRUE
#define BIND_LocaleEntry_INITIALIZE FALSE

#define BIND_MappingEntry_TYPE TRUE
#define BIND_MappingEntry_INITIALIZE FALSE

#define BIND_MappingRange_TYPE TRUE
#define BIND_MappingRange_INITIALIZE FALSE


#endif
